
import { ScrollArea } from "@/components/ui/scroll-area";
import { cn } from "@/lib/utils";
import { DiffChange } from "@/lib/diff-parser";
import { ArrowRight, ArrowLeft, Check, FileText, Trash2, Sparkles, PieChart, ChevronUp, ChevronDown } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { AISummaryPanel } from "@/components/ai/AISummary";
import { AISummary } from "@/types/document";

import { translations } from "@/lib/i18n";
import { useComparisonStore } from "@/stores/comparison-store";

interface ChangesSidebarProps {
    changes: DiffChange[];
    selectedIndex: number;
    onSelectChange: (index: number) => void; // Changed from onChange to align with usage
    aiSummary: AISummary | null;
    isAiLoading: boolean;
    onGenerateAi: () => void;
    canGenerateAi: boolean;
    language: 'en' | 'vi';
    width?: number;
    stats?: { additions: number, deletions: number, modifications: number }; // Added stats prop
}

export function ChangesSidebar({
    changes,
    selectedIndex, // Match usage in Page.tsx
    onSelectChange, // Match usage in Page.tsx
    aiSummary,
    isAiLoading,
    onGenerateAi,
    canGenerateAi,
    language,
    width = 320,
    stats
}: ChangesSidebarProps) {

    // We can use the prop language, but to consistently use t, let's grab it or just use the prop to index translations
    // Since language is passed as prop, we use it directly:
    const t = translations[language];

    const addedCount = stats?.additions ?? changes.filter(c => c.type === 'added').length;
    const removedCount = stats?.deletions ?? changes.filter(c => c.type === 'removed').length;
    const modifiedCount = stats?.modifications ?? changes.filter(c => c.type === 'modified').length;

    return (
        <div
            className="border-l bg-card flex flex-col h-full shadow-xl z-20 shrink-0 transition-[width] duration-0 ease-linear"
            style={{ width }}
        >

            {/* Top Section: AI Panel (Fixed/Shrink) */}
            <div className="shrink-0 border-b p-4 pb-2 bg-muted/10">
                <AISummaryPanel
                    summary={aiSummary}
                    isLoading={isAiLoading}
                    onGenerate={onGenerateAi}
                    language={language}
                    canGenerate={canGenerateAi}
                    autoGenerated={false}
                    compact={true}
                />
            </div>

            {/* Changes List Section */}
            <div className="flex-1 flex flex-col min-h-0 relative">
                {/* Toolbar with Embedded Stats */}
                <div className="flex items-center justify-between px-3 py-2 shrink-0 border-b bg-muted/40 sticky top-0 z-10 h-12">

                    {/* Left: Title + Total */}
                    <div className="flex items-center gap-2">
                        <span className="text-xs font-semibold text-foreground/80 uppercase tracking-tight">{t.changes}</span>
                        <Badge variant="secondary" className="h-5 px-1.5 text-[10px] min-w-[20px] justify-center">{changes.length}</Badge>
                    </div>

                    {/* Center: Stats Pills */}
                    <div className="flex items-center gap-1.5 mx-2">
                        {addedCount > 0 && (
                            <div className="flex items-center gap-1 text-[10px] font-medium text-green-600 bg-green-500/10 px-1.5 py-0.5 rounded-full ring-1 ring-green-500/20" title="Added">
                                <span>+</span>{addedCount}
                            </div>
                        )}
                        {modifiedCount > 0 && (
                            <div className="flex items-center gap-1 text-[10px] font-medium text-amber-600 bg-amber-500/10 px-1.5 py-0.5 rounded-full ring-1 ring-amber-500/20" title="Values Changed">
                                <span>~</span>{modifiedCount}
                            </div>
                        )}
                        {removedCount > 0 && (
                            <div className="flex items-center gap-1 text-[10px] font-medium text-red-600 bg-red-500/10 px-1.5 py-0.5 rounded-full ring-1 ring-red-500/20" title="Removed">
                                <span>-</span>{removedCount}
                            </div>
                        )}
                    </div>

                    {/* Right: Nav */}
                    <div className="flex items-center gap-0.5">
                        <Button
                            variant="ghost"
                            size="icon"
                            className="h-6 w-6"
                            onClick={() => onSelectChange(Math.max(0, selectedIndex - 1))}
                            disabled={selectedIndex <= 0}
                            title="Previous Change"
                        >
                            <ChevronUp className="w-3.5 h-3.5" />
                        </Button>
                        <Button
                            variant="ghost"
                            size="icon"
                            className="h-6 w-6"
                            onClick={() => onSelectChange(Math.min(changes.length - 1, selectedIndex + 1))}
                            disabled={selectedIndex >= changes.length - 1}
                            title="Next Change"
                        >
                            <ChevronDown className="w-3.5 h-3.5" />
                        </Button>
                    </div>
                </div>

                {/* Change List */}
                <div className="flex-1 overflow-y-auto scroll-smooth p-2 space-y-2 pb-20">
                    {changes.length === 0 ? (
                        <div className="flex flex-col items-center justify-center h-48 text-muted-foreground text-center p-8">
                            <FileText className="w-10 h-10 mb-3 opacity-20" />
                            <p className="text-sm">No text changes detected</p>
                        </div>
                    ) : (
                        <>
                            {changes.map((change, idx) => (
                                <button
                                    key={change.id || idx}
                                    onClick={() => onSelectChange(idx)}
                                    className={cn(
                                        "w-full text-left p-3 rounded-lg text-xs leading-relaxed transition-all border group relative",
                                        idx === selectedIndex
                                            ? "bg-primary/5 border-primary shadow-sm ring-1 ring-primary/20"
                                            : "bg-card border-border hover:border-primary/50 hover:bg-muted/50"
                                    )}
                                >
                                    <div className="flex items-center justify-between gap-2 mb-1.5">
                                        {change.type === 'added' ? (
                                            <Badge variant="outline" className="bg-green-500/10 text-green-700 border-green-200 hover:bg-green-500/20 px-1.5 py-0 h-5 text-[9px] font-bold">
                                                ADDED
                                            </Badge>
                                        ) : change.type === 'modified' ? (
                                            <Badge variant="outline" className="bg-amber-500/10 text-amber-700 border-amber-200 hover:bg-amber-500/20 px-1.5 py-0 h-5 text-[9px] font-bold">
                                                MODIFIED
                                            </Badge>
                                        ) : (
                                            <Badge variant="outline" className="bg-red-500/10 text-red-700 border-red-200 hover:bg-red-500/20 px-1.5 py-0 h-5 text-[9px] font-bold">
                                                REMOVED
                                            </Badge>
                                        )}
                                        <span className="text-[9px] font-mono text-muted-foreground opacity-50">#{idx + 1}</span>
                                    </div>

                                    <div className="text-foreground/90 font-mono bg-white/50 dark:bg-black/20 p-2 rounded border border-black/5 dark:border-white/5 group-hover:bg-background transition-colors text-xs space-y-1">
                                        {change.type === 'removed' ? (
                                            <div className="line-through opacity-70 break-words">{change.text.substring(0, 100)}</div>
                                        ) : change.type === 'added' ? (
                                            <div className="break-words">{change.text.substring(0, 100)}</div>
                                        ) : (
                                            <>
                                                <div className="line-through opacity-70 text-red-700/70 break-words">{change.oldText?.substring(0, 80)}</div>
                                                <div className="text-green-700/90 break-words">{change.text.substring(0, 80)}</div>
                                            </>
                                        )}
                                    </div>
                                </button>
                            ))}
                        </>
                    )}
                </div>
            </div>
        </div>
    );
}
