'use client';

import { Sparkles, Loader2, ChevronDown, ChevronUp, Zap, AlertCircle } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { cn } from '@/lib/utils';
import type { AISummary } from '@/types/document';
import { translations, Language } from '@/lib/i18n';

interface AISummaryPanelProps {
    summary: AISummary | null;
    isLoading: boolean;
    onGenerate: () => void;
    language: Language;
    canGenerate: boolean;
    autoGenerated?: boolean;
}

export function AISummaryPanel({
    summary,
    isLoading,
    onGenerate,
    language,
    canGenerate,
    autoGenerated = false,
    compact = false, // New prop
}: AISummaryPanelProps & { compact?: boolean }) {
    const t = translations[language];

    const impactColors = {
        minor: 'bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-300 border-blue-200',
        moderate: 'bg-yellow-100 text-yellow-700 dark:bg-yellow-900/30 dark:text-yellow-300 border-yellow-200',
        major: 'bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-300 border-red-200',
    };

    const impactLabels = {
        minor: t.minor,
        moderate: t.moderate,
        major: t.major,
    };

    return (
        <div className={cn("ai-summary-card", compact && "border-none shadow-none bg-transparent")}>
            {/* Header - Hidden in compact mode or simplified */}
            {!compact && (
                <div className="ai-summary-header flex items-center justify-between py-4 px-6 border-b border-purple-500/20">
                    <div className="flex items-center gap-3">
                        <div className="w-10 h-10 rounded-lg bg-gradient-to-br from-purple-500 to-pink-500 flex items-center justify-center shadow-lg">
                            <Sparkles className="w-5 h-5 text-white" />
                        </div>
                        <div>
                            <h3 className="font-semibold text-lg">{t.aiSummary}</h3>
                            {autoGenerated && (
                                <p className="text-xs text-muted-foreground flex items-center gap-1">
                                    <Zap className="w-3 h-3" />
                                    {language === 'vi' ? 'Tự động tạo' : 'Auto-generated'}
                                </p>
                            )}
                        </div>
                    </div>

                    {summary && (
                        <Badge className={cn("text-sm font-medium", impactColors[summary.impactLevel])}>
                            {impactLabels[summary.impactLevel]}
                        </Badge>
                    )}
                </div>
            )}

            {/* Compact Header */}
            {compact && (
                <div className="flex items-center justify-between mb-2">
                    <h3 className="font-semibold text-xs uppercase tracking-wider text-muted-foreground flex items-center gap-2">
                        <Sparkles className="w-3.5 h-3.5" />
                        {t.aiSummary}
                    </h3>
                    {summary && (
                        <Badge variant="outline" className={cn("text-[10px] h-5 px-1.5", impactColors[summary.impactLevel])}>
                            {impactLabels[summary.impactLevel]}
                        </Badge>
                    )}
                </div>
            )}

            {/* Content */}
            <div className="p-6">
                {isLoading && (
                    <div className="flex flex-col items-center justify-center py-12 space-y-4">
                        <div className="relative">
                            <div className="w-16 h-16 rounded-full bg-gradient-to-br from-purple-500/20 to-pink-500/20 flex items-center justify-center">
                                <Loader2 className="w-8 h-8 animate-spin text-purple-500" />
                            </div>
                            <div className="absolute inset-0 rounded-full bg-gradient-to-br from-purple-500 to-pink-500 opacity-20 blur-xl animate-pulse" />
                        </div>
                        <div className="text-center">
                            <p className="font-medium">{t.generating}</p>
                            <p className="text-sm text-muted-foreground mt-1">
                                {language === 'vi'
                                    ? 'AI đang phân tích các thay đổi...'
                                    : 'AI is analyzing the changes...'}
                            </p>
                        </div>
                    </div>
                )}

                {!isLoading && !summary && !autoGenerated && (
                    <div className="text-center py-8">
                        <div className="w-16 h-16 mx-auto mb-4 rounded-full bg-gradient-to-br from-purple-500/10 to-pink-500/10 flex items-center justify-center">
                            <Sparkles className="w-8 h-8 text-purple-500/50" />
                        </div>
                        <p className="text-muted-foreground mb-4">
                            {language === 'vi'
                                ? 'Tạo tóm tắt bằng AI để xem tổng quan về các thay đổi'
                                : 'Generate an AI summary to get an overview of the changes'}
                        </p>
                        <Button
                            onClick={onGenerate}
                            disabled={!canGenerate}
                            className="gradient-bg hover:opacity-90"
                        >
                            <Sparkles className="w-4 h-4 mr-2" />
                            {t.generateSummary}
                        </Button>
                    </div>
                )}

                {!isLoading && !summary && autoGenerated && (
                    <div className="flex items-center gap-3 py-4 px-4 rounded-xl bg-orange-500/10 border border-orange-500/20">
                        <AlertCircle className="w-5 h-5 text-orange-500 flex-shrink-0" />
                        <p className="text-sm text-orange-600 dark:text-orange-400">
                            {language === 'vi'
                                ? 'Không thể tạo tóm tắt AI. Vui lòng kiểm tra kết nối mạng và API key.'
                                : 'Could not generate AI summary. Please check your network connection and API key.'}
                        </p>
                    </div>
                )}

                {summary && !isLoading && (
                    <div className="space-y-6">
                        {/* Summary Text */}
                        <div className="p-4 rounded-xl bg-gradient-to-br from-purple-500/5 to-pink-500/5 border border-purple-500/10">
                            <p className="text-foreground leading-relaxed text-lg">
                                {language === 'vi' && summary.summaryVi
                                    ? summary.summaryVi
                                    : summary.summary}
                            </p>
                        </div>

                        {/* Key Changes */}
                        {summary.keyChanges.length > 0 && (
                            <div>
                                <h4 className="font-semibold text-sm text-muted-foreground uppercase tracking-wide mb-3 flex items-center gap-2">
                                    <Zap className="w-4 h-4" />
                                    {t.keyChanges}
                                </h4>
                                <ul className="space-y-2">
                                    {summary.keyChanges.map((change, index) => (
                                        <li
                                            key={index}
                                            className="flex items-start gap-3 p-3 rounded-lg bg-secondary/50 hover:bg-secondary transition-colors"
                                        >
                                            <span className="flex-shrink-0 w-6 h-6 rounded-full bg-gradient-to-br from-purple-500 to-pink-500 text-white text-xs flex items-center justify-center font-semibold">
                                                {index + 1}
                                            </span>
                                            <span className="text-sm leading-relaxed">{change}</span>
                                        </li>
                                    ))}
                                </ul>
                            </div>
                        )}
                    </div>
                )}
            </div>
        </div>
    );
}
